name: www-hakyll-flare-timing
version: 0.2.0
synopsis: flaretiming.com
description: Static site generator for flaretiming.com
category: web
homepage: https://github.com/flaretiming/flaretiming/tree/develop#readme
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
copyright: © 2017-2018 Phil de Joux, © 2017-2018 Block Scope Limited
license: MPL-2.0
license-file: LICENSE
tested-with: GHC == 8.2.2
github: blockscope/blockscope
extra-source-files:
- package.dhall
- package.yaml
- changelog.md
- README.md
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PackageImports
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- TupleSections
- UndecidableInstances
ghc-options:
- -Wall
- -Werror
dependencies:
- base >=4.10.1.0 && <5
executables:
  site:
    main: site.hs
    source-dirs: www-hakyll
    dependencies:
    - base
    - hakyll
    - pandoc
    - blaze-html
tests:
  hlint:
    main: HLint.hs
    source-dirs:
    - .
    - test-suite-hlint
    dependencies:
    - base
    - hakyll
    - pandoc
    - blaze-html
    - hlint

